/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Assets {
  static const String cart = "assets/icons/cart.png";
  static const String flash = "assets/icons/flash.png";
  static const String notification = "assets/icons/notification.png";
  static const String plusJakartaSans_Regular = "assets/fonts/PlusJakartaSans-regular.ttf";
  static const String profile = "assets/icons/profile.png";
  static const String search = "assets/icons/search.png";
}
